# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/FlashcardEditLine.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FlashcardEditLine(object):
    def setupUi(self, FlashcardEditLine):
        FlashcardEditLine.setObjectName("FlashcardEditLine")
        FlashcardEditLine.resize(924, 70)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(FlashcardEditLine)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(FlashcardEditLine)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edit_question_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_question_button.sizePolicy().hasHeightForWidth())
        self.edit_question_button.setSizePolicy(sizePolicy)
        self.edit_question_button.setObjectName("edit_question_button")
        self.horizontalLayout_3.addWidget(self.edit_question_button)
        self.question_image = QSvgWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_image.sizePolicy().hasHeightForWidth())
        self.question_image.setSizePolicy(sizePolicy)
        self.question_image.setMinimumSize(QtCore.QSize(0, 50))
        self.question_image.setObjectName("question_image")
        self.horizontalLayout_3.addWidget(self.question_image)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.edit_answer_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_answer_button.sizePolicy().hasHeightForWidth())
        self.edit_answer_button.setSizePolicy(sizePolicy)
        self.edit_answer_button.setObjectName("edit_answer_button")
        self.horizontalLayout_3.addWidget(self.edit_answer_button)
        self.answer_image = QSvgWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_image.sizePolicy().hasHeightForWidth())
        self.answer_image.setSizePolicy(sizePolicy)
        self.answer_image.setMinimumSize(QtCore.QSize(0, 50))
        self.answer_image.setObjectName("answer_image")
        self.horizontalLayout_3.addWidget(self.answer_image)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.remove_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_button.sizePolicy().hasHeightForWidth())
        self.remove_button.setSizePolicy(sizePolicy)
        self.remove_button.setObjectName("remove_button")
        self.horizontalLayout_3.addWidget(self.remove_button)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(FlashcardEditLine)
        QtCore.QMetaObject.connectSlotsByName(FlashcardEditLine)

    def retranslateUi(self, FlashcardEditLine):
        _translate = QtCore.QCoreApplication.translate
        FlashcardEditLine.setWindowTitle(_translate("FlashcardEditLine", "Form"))
        self.edit_question_button.setText(_translate("FlashcardEditLine", "Edit"))
        self.edit_answer_button.setText(_translate("FlashcardEditLine", "Edit"))
        self.remove_button.setText(_translate("FlashcardEditLine", "Remove"))
from PyQt5.QtSvg import QSvgWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FlashcardEditLine = QtWidgets.QWidget()
    ui = Ui_FlashcardEditLine()
    ui.setupUi(FlashcardEditLine)
    FlashcardEditLine.show()
    sys.exit(app.exec_())
