# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(710, 452)
        self.verticalLayout = QtWidgets.QVBoxLayout(Home)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QLabel(Home)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_flashcards = QtWidgets.QPushButton(Home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_flashcards.sizePolicy().hasHeightForWidth())
        self.button_flashcards.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.button_flashcards.setFont(font)
        self.button_flashcards.setIconSize(QtCore.QSize(28, 28))
        self.button_flashcards.setObjectName("button_flashcards")
        self.gridLayout.addWidget(self.button_flashcards, 0, 0, 1, 1)
        self.button_problems = QtWidgets.QPushButton(Home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_problems.sizePolicy().hasHeightForWidth())
        self.button_problems.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.button_problems.setFont(font)
        self.button_problems.setObjectName("button_problems")
        self.gridLayout.addWidget(self.button_problems, 0, 1, 1, 1)
        self.button_calculator = QtWidgets.QPushButton(Home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_calculator.sizePolicy().hasHeightForWidth())
        self.button_calculator.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.button_calculator.setFont(font)
        self.button_calculator.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_calculator.setIconSize(QtCore.QSize(52, 54))
        self.button_calculator.setCheckable(False)
        self.button_calculator.setChecked(False)
        self.button_calculator.setObjectName("button_calculator")
        self.gridLayout.addWidget(self.button_calculator, 1, 0, 1, 1)
        self.button_graph = QtWidgets.QPushButton(Home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_graph.sizePolicy().hasHeightForWidth())
        self.button_graph.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.button_graph.setFont(font)
        self.button_graph.setObjectName("button_graph")
        self.gridLayout.addWidget(self.button_graph, 1, 1, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Form"))
        self.title.setText(_translate("Home", "Math!"))
        self.button_flashcards.setText(_translate("Home", "Flashcards"))
        self.button_problems.setText(_translate("Home", "Problems"))
        self.button_calculator.setText(_translate("Home", "Calculator"))
        self.button_graph.setText(_translate("Home", "Graph"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QWidget()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
