# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/TextEntryDerivative.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextEntryDerivative(object):
    def setupUi(self, TextEntryDerivative):
        TextEntryDerivative.setObjectName("TextEntryDerivative")
        TextEntryDerivative.resize(902, 274)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TextEntryDerivative.sizePolicy().hasHeightForWidth())
        TextEntryDerivative.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TextEntryDerivative)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(TextEntryDerivative)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(TextEntryDerivative)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(TextEntryDerivative)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.variable = QtWidgets.QComboBox(TextEntryDerivative)
        self.variable.setObjectName("variable")
        self.variable.addItem("")
        self.variable.addItem("")
        self.variable.addItem("")
        self.variable.addItem("")
        self.variable.addItem("")
        self.horizontalLayout_2.addWidget(self.variable)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.text_entry = QtWidgets.QLineEdit(TextEntryDerivative)
        self.text_entry.setObjectName("text_entry")
        self.horizontalLayout.addWidget(self.text_entry)
        self.button_enter = QtWidgets.QPushButton(TextEntryDerivative)
        self.button_enter.setObjectName("button_enter")
        self.horizontalLayout.addWidget(self.button_enter)

        self.retranslateUi(TextEntryDerivative)
        QtCore.QMetaObject.connectSlotsByName(TextEntryDerivative)

    def retranslateUi(self, TextEntryDerivative):
        _translate = QtCore.QCoreApplication.translate
        TextEntryDerivative.setWindowTitle(_translate("TextEntryDerivative", "Form"))
        self.label.setText(_translate("TextEntryDerivative", "d"))
        self.label_2.setText(_translate("TextEntryDerivative", "d"))
        self.variable.setItemText(0, _translate("TextEntryDerivative", "x"))
        self.variable.setItemText(1, _translate("TextEntryDerivative", "t"))
        self.variable.setItemText(2, _translate("TextEntryDerivative", "u"))
        self.variable.setItemText(3, _translate("TextEntryDerivative", "y"))
        self.variable.setItemText(4, _translate("TextEntryDerivative", "θ"))
        self.button_enter.setText(_translate("TextEntryDerivative", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TextEntryDerivative = QtWidgets.QWidget()
    ui = Ui_TextEntryDerivative()
    ui.setupUi(TextEntryDerivative)
    TextEntryDerivative.show()
    sys.exit(app.exec_())
