# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/TextEntryIntegral.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextEntryIntegral(object):
    def setupUi(self, TextEntryIntegral):
        TextEntryIntegral.setObjectName("TextEntryIntegral")
        TextEntryIntegral.resize(885, 152)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TextEntryIntegral.sizePolicy().hasHeightForWidth())
        TextEntryIntegral.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TextEntryIntegral)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(TextEntryIntegral)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.text_entry = QtWidgets.QLineEdit(TextEntryIntegral)
        self.text_entry.setObjectName("text_entry")
        self.horizontalLayout.addWidget(self.text_entry)
        self.label_2 = QtWidgets.QLabel(TextEntryIntegral)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.variable = QtWidgets.QComboBox(TextEntryIntegral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variable.sizePolicy().hasHeightForWidth())
        self.variable.setSizePolicy(sizePolicy)
        self.variable.setObjectName("variable")
        self.variable.addItem("")
        self.variable.addItem("")
        self.variable.addItem("")
        self.variable.addItem("")
        self.variable.addItem("")
        self.horizontalLayout.addWidget(self.variable)
        self.button_enter = QtWidgets.QPushButton(TextEntryIntegral)
        self.button_enter.setObjectName("button_enter")
        self.horizontalLayout.addWidget(self.button_enter)

        self.retranslateUi(TextEntryIntegral)
        QtCore.QMetaObject.connectSlotsByName(TextEntryIntegral)

    def retranslateUi(self, TextEntryIntegral):
        _translate = QtCore.QCoreApplication.translate
        TextEntryIntegral.setWindowTitle(_translate("TextEntryIntegral", "Form"))
        self.label.setText(_translate("TextEntryIntegral", "∫"))
        self.label_2.setText(_translate("TextEntryIntegral", "d"))
        self.variable.setItemText(0, _translate("TextEntryIntegral", "x"))
        self.variable.setItemText(1, _translate("TextEntryIntegral", "u"))
        self.variable.setItemText(2, _translate("TextEntryIntegral", "t"))
        self.variable.setItemText(3, _translate("TextEntryIntegral", "y"))
        self.variable.setItemText(4, _translate("TextEntryIntegral", "θ"))
        self.button_enter.setText(_translate("TextEntryIntegral", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TextEntryIntegral = QtWidgets.QWidget()
    ui = Ui_TextEntryIntegral()
    ui.setupUi(TextEntryIntegral)
    TextEntryIntegral.show()
    sys.exit(app.exec_())
