# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/TextEntrySum.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextEntrySum(object):
    def setupUi(self, TextEntrySum):
        TextEntrySum.setObjectName("TextEntrySum")
        TextEntrySum.resize(619, 295)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TextEntrySum)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(TextEntrySum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(TextEntrySum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.variable = QtWidgets.QComboBox(TextEntrySum)
        self.variable.setObjectName("variable")
        self.variable.addItem("")
        self.variable.addItem("")
        self.variable.addItem("")
        self.horizontalLayout_2.addWidget(self.variable)
        self.label_3 = QtWidgets.QLabel(TextEntrySum)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.value = QtWidgets.QLineEdit(TextEntrySum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value.sizePolicy().hasHeightForWidth())
        self.value.setSizePolicy(sizePolicy)
        self.value.setMaximumSize(QtCore.QSize(24, 16777215))
        self.value.setObjectName("value")
        self.horizontalLayout_2.addWidget(self.value)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.text_entry = QtWidgets.QLineEdit(TextEntrySum)
        self.text_entry.setObjectName("text_entry")
        self.horizontalLayout.addWidget(self.text_entry)
        self.button_enter = QtWidgets.QPushButton(TextEntrySum)
        self.button_enter.setObjectName("button_enter")
        self.horizontalLayout.addWidget(self.button_enter)

        self.retranslateUi(TextEntrySum)
        QtCore.QMetaObject.connectSlotsByName(TextEntrySum)

    def retranslateUi(self, TextEntrySum):
        _translate = QtCore.QCoreApplication.translate
        TextEntrySum.setWindowTitle(_translate("TextEntrySum", "Form"))
        self.label_2.setText(_translate("TextEntrySum", "∞"))
        self.label.setText(_translate("TextEntrySum", "Σ"))
        self.variable.setItemText(0, _translate("TextEntrySum", "n"))
        self.variable.setItemText(1, _translate("TextEntrySum", "k"))
        self.variable.setItemText(2, _translate("TextEntrySum", "i"))
        self.label_3.setText(_translate("TextEntrySum", "="))
        self.button_enter.setText(_translate("TextEntrySum", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TextEntrySum = QtWidgets.QWidget()
    ui = Ui_TextEntrySum()
    ui.setupUi(TextEntrySum)
    TextEntrySum.show()
    sys.exit(app.exec_())
